// Renders the conformance README from raw probe output.
//   node gen-report.mjs results.json > README.md
import { readFileSync } from "fs";

const d = JSON.parse(readFileSync(process.argv[2], "utf8"));
const R = d.results;
const by = (v) => R.filter((r) => r.verdict === v);
const pct = (n) => ((n / R.length) * 100).toFixed(1);

const conformant = by("conformant");
const partial = by("partial-2026");
const statelessIsh = by("stateless-ish-legacy");
const legacy = by("legacy-stateful");
const auth = by("auth-required");
const unreachable = by("unreachable").concat(by("error"));
const probed = R.length - auth.length - unreachable.length;

const rows = (list) =>
  list
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((r) => {
      const c = r.checks || {};
      const y = (v) => (v === true ? "✅" : v === false ? "❌" : "—");
      return `| \`${r.name}\` | ${y(c.serverDiscover)} | ${y(c.coldToolsList)} | ${y(!c.issuesSessionId)} | ${y(c.resultType === "complete")} | ${y(c.ttlMs !== null && c.cacheScope !== null)} | ${y(c.badVersionCode === -32022)} | ${y(c.headerMismatchCode === -32020)} |`;
    })
    .join("\n");

const HEAD = `| Server | \`server/discover\` | Cold \`tools/list\` | No session id | \`resultType\` | \`ttlMs\`+\`cacheScope\` | \`-32022\` | \`-32020\` |
| --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |`;

// Which MUST trips implementers up most — the actually useful signal for maintainers.
const tally = {};
for (const r of R) for (const f of r.failures || []) tally[f] = (tally[f] || 0) + 1;
const ranked = Object.entries(tally).sort((a, b) => b[1] - a[1]);

console.log(`# MCP 2026-07-28 Stateless Conformance

Machine-checked conformance of public MCP servers against the
[2026-07-28 specification](https://modelcontextprotocol.io/specification/2026-07-28/changelog).

Every cell below is the result of an HTTP request made against the live endpoint.
No self-reported badges, no vendor claims. Re-run it yourself:

\`\`\`bash
node conformance.mjs servers.json results.jsonl
\`\`\`

**Probed:** ${d.probedAt} · **Corpus:** ${R.length} remote servers from the official MCP registry

## Scoreboard

| Verdict | Count | Share |
| --- | ---: | ---: |
| ✅ Fully conformant | **${conformant.length}** | ${pct(conformant.length)}% |
| 🟡 Implements \`server/discover\`, fails ≥1 MUST | ${partial.length} | ${pct(partial.length)}% |
| 🟠 Answers cold requests, no 2026 surface | ${statelessIsh.length} | ${pct(statelessIsh.length)}% |
| 🔴 Legacy stateful | ${legacy.length} | ${pct(legacy.length)}% |
| 🔒 Auth-gated (not probeable) | ${auth.length} | ${pct(auth.length)}% |
| ⚫ Unreachable | ${unreachable.length} | ${pct(unreachable.length)}% |

Of **${probed}** servers that answered an unauthenticated request,
**${conformant.length}** (${probed ? ((conformant.length / probed) * 100).toFixed(1) : 0}%) fully conform.

> **Read the server count with care.** Adoption is concentrated: the
> ${conformant.length + partial.length} servers with any 2026 surface come from just
> **${new Set([...conformant, ...partial].map((r) => r.name.split("/")[0])).size} operators**, because
> one vendor may deploy the same codebase to many endpoints. Operator count is the
> honest adoption signal; server count overstates it.

### By operator

| Operator | Servers with 2026 surface | Fully conformant |
| --- | ---: | ---: |
${(() => {
  const ops = {};
  for (const r of [...conformant, ...partial]) {
    const o = r.name.split("/")[0];
    ops[o] = ops[o] || { n: 0, c: 0 };
    ops[o].n++;
    if (r.verdict === "conformant") ops[o].c++;
  }
  return Object.entries(ops)
    .sort((a, b) => b[1].c - a[1].c || b[1].n - a[1].n)
    .map(([o, v]) => `| \`${o}\` | ${v.n} | ${v.c} |`)
    .join("\n");
})()}

## What each check means

| Check | Spec rule | Why it matters |
| --- | --- | --- |
| \`server/discover\` | major-3 | Servers **MUST** implement it. The single clearest 2026 marker. |
| Cold \`tools/list\` | major-2 | No \`initialize\` handshake — a cold instance must answer request #1. |
| No session id | major-1 | \`Mcp-Session-Id\` is removed; its presence means sticky routing. |
| \`resultType\` | major-8 | All results **MUST** carry it. |
| \`ttlMs\`+\`cacheScope\` | minor-5 | List results **MUST** be cacheable. |
| \`-32022\` | minor-12 | Version mismatch **MUST** use \`UnsupportedProtocolVersion\`. |
| \`-32020\` | minor-4/12 | \`Mcp-Method\` header/body mismatch **MUST** be rejected. |

## ✅ Fully conformant (${conformant.length})

${conformant.length ? HEAD + "\n" + rows(conformant) : "_None yet._"}

## 🟡 Partial — implements \`server/discover\` but fails a MUST (${partial.length})

${partial.length ? HEAD + "\n" + rows(partial) : "_None._"}

## Most-failed rules

| Rule | Servers failing |
| --- | ---: |
${ranked.map(([k, v]) => `| ${k} | ${v} |`).join("\n")}

---

Generated by \`gen-report.mjs\`. Corpus: official MCP registry. Contributions: open a PR adding
your endpoint to \`servers.json\` — CI probes it and regenerates this table.
`);
